In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("ML1_dataset.csv")
data.head(8)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000

In [3]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [4]:
print(round(data["LotArea"].mean()))
print(round(data["SalePrice"].max()))

10517
755000

In [5]:
newest_house = data["YearBuilt"].max()
newest_house

2010

#### Newest house is not that new: if the reason is explanation1 => The model may still be useful for predicting prices of existing homes, but less reliable for newer constructions........if the reason is explanation 2 => The models trustworthyness is doubtfull as the data is outdated and the model do not know about the current market prices ####

In [6]:
data['YearBuilt'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 1460 entries, 0 to 1459
Series name: YearBuilt
Non-Null Count  Dtype
--------------  -----
1460 non-null   int64
dtypes: int64(1)
memory usage: 11.5 KB

In [7]:
data.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [8]:
y = data.loc[:, ['SalePrice']]
X = data.loc[:, ['LotArea','YearBuilt','1stFlrSF','2ndFlrSF','FullBath','BedroomAbvGr','TotRmsAbvGrd']]
new_data = pd.concat([X, y], axis=1)

In [9]:
new_data.isnull().sum()

LotArea         0
YearBuilt       0
1stFlrSF        0
2ndFlrSF        0
FullBath        0
BedroomAbvGr    0
TotRmsAbvGrd    0
SalePrice       0
dtype: int64

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeClassifier
model1 = LinearRegression()
model2 = DecisionTreeClassifier()

In [11]:
model1.fit(X,y)

LinearRegression()

In [12]:
model2.fit(X,y)

DecisionTreeClassifier()

In [13]:
new_data.head(8)

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd,SalePrice
0,8450,2003,856,854,2,3,8,208500
1,9600,1976,1262,0,2,3,6,181500
2,11250,2001,920,866,2,3,6,223500
3,9550,1915,961,756,1,3,7,140000
4,14260,2000,1145,1053,2,4,9,250000
5,14115,1993,796,566,1,1,5,143000
6,10084,2004,1694,0,2,3,7,307000
7,10382,1973,1107,983,2,3,7,200000

In [14]:
lin_reg_pred = pd.DataFrame(model1.predict(X))
lin_reg_pred.head(8)

               0
0  219164.643595
1  161876.161280
2  217670.671997
3  141704.326008
4  256836.177254
5  204571.362116
6  242197.361321
7  229004.455445

In [15]:
dec_tree_pred = pd.DataFrame(model2.predict(X))
dec_tree_pred.head(8)

        0
0  208500
1  181500
2  223500
3  140000
4  250000
5  143000
6  307000
7  200000

#### Yeah the linear regression model predicted somewhat deviated values but decission tree model predicted exact value ###
#### it is because linear regression fits a single line to the training data, and the predictions are on this line, so it is doing underfitting while decission tree is doing overfitting #####

In [16]:
from sklearn.metrics import mean_absolute_error
mae_lin_reg = mean_absolute_error(y, lin_reg_pred)
mae_dec_tree = mean_absolute_error(y, dec_tree_pred)

In [17]:
print(mae_lin_reg)
print(mae_dec_tree)

27667.254099950267
61.03013698630137

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=1)
model2.fit(X_train, y_train)

DecisionTreeClassifier()

In [19]:
dec_tree_pred2 = pd.DataFrame(model2.predict(X_test))
dec_tree_pred2

          0
0    186500
1    184000
2    130000
3     92000
4    155000
..      ...
433  246578
434  192500
435  127500
436  181000
437  262500

[438 rows x 1 columns]

In [20]:
y_test

      SalePrice
258      231500
267      179500
288      122000
649       84500
1233     142000
...         ...
793      225000
631      209500
1172     171900
1167     173000
529      200624

[438 rows x 1 columns]

In [21]:
mae_dec_tree2 = mean_absolute_error(y_test, dec_tree_pred2)
print(mae_dec_tree2)

33966.07534246575

#### Observation: mae increased drastically. It is because earlier we were predicting the data which the model has already seen so it was doing overfitting. But now we are predicting on a new data, so the chances of error has increased. ####

#### there isn't any general rule whether the MAE is good or not, it depends on the context for which we are training the model. In our context the MAE value is pretty lesser tham the exact outcome values, so our model is satisfactory though it is not very good. ####